name: Realease
on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 450
    env:
      CIBW_SKIP: "cp111-* cp110-*"

    steps:
    - name: Checkout
      uses: actions/checkout@v3  
  
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:  
        python-version: "3.11" 
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install cibuildwheel==2.15.0 Cython==3.0.2
  
    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse

    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl
        retention-days: 1
