name: Realease
on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ ubuntu-latest windows-latest macos-latest ]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 450
    env:
      CIBW_BUILD: "cp310-* cp311-* cp312-*_x86_64"
    steps:
    - name: Checkout
      uses: actions/checkout@v3  
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:  
        python-version: "3.11" 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install cibuildwheel==2.15.0 Cython==3.0.2
    - name: Build wheels
      run: python -m cibuildwheel --output-dir dist
    - uses: actions/upload-artifact@v3
      with:
        path: ./dist/*.whl
        retention-days: 1

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements_dev.txt
      - name: Build tarball
        run: |
          make build_ext
          make dist
      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.tar.gz
          retention-days: 1
  
  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ SECRETS.PYPI_TOKEN }}
